# Every time we push to master, travis CI will run the steps
# defined in this file to perform the build of the application

sudo: required
services:
  - docker

# Run before test are done
before_install:
  - docker build -f Dockerfile.dev -t docker-ci-test .

# Series of cmds that run when travis CI gets executed
# If doesn't return status_code == 0, travis assumes that the tests failed
script:
  - echo "run tests if any"     # perform tests
  - docker run docker-ci-test python test.py

# Tells travis how to deploy the application to the server
# (Needs to be changed for GCP)
deploy:
  provider: script
  script: chmod u+x deploy.sh
  on:
    branch: main    # every time we push to main, makes the deploy

