# Kubernetes cluster deploy file
apiVersion: "apps/v1"
kind: Deployment
metadata:
  name  : simple-app
  labels:
    app: simple-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-app
  template:
    metadata:
      labels:
        app: simple-app
    spec:
      containers:
      - name: simple-app
        image: gcr.io/august-bot-299118/simple-app:latest
--- 
# A load balancer is type of service which will expose an IP and route the requests to this IP to the internal pods.     
apiVersion: v1
kind: Service
metadata:
  name: simple-app  
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: simple-app  